CREATE TABLE `historico_assinaturas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `documento_id` varchar(64) DEFAULT NULL,
  `requerimento_id` int(11) DEFAULT NULL,
  `admin_id` int(11) DEFAULT NULL,
  `evento` varchar(30) NOT NULL,
  `origem` varchar(30) DEFAULT NULL,
  `status` enum('sucesso','erro') NOT NULL,
  `email_destino` varchar(191) DEFAULT NULL,
  `codigo_hash` varchar(64) DEFAULT NULL,
  `codigo_ultimos` varchar(2) DEFAULT NULL,
  `ip` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `accept_language` varchar(50) DEFAULT NULL,
  `host` varchar(191) DEFAULT NULL,
  `nome_arquivo` varchar(255) DEFAULT NULL,
  `hash_documento` varchar(64) DEFAULT NULL,
  `erro` text DEFAULT NULL,
  `data_evento` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `documento_id` (`documento_id`),
  KEY `requerimento_id` (`requerimento_id`),
  KEY `admin_id` (`admin_id`),
  KEY `evento` (`evento`),
  KEY `status` (`status`),
  KEY `data_evento` (`data_evento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
